name: Tests

on:
  push:
    paths-ignore:
      - .github/**
      - .vscode/**
      - .editorconfig
      - .npmignore
      - '**.md'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: '12' }
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: v1-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-node-
      - run: npm install
      - run: npm test
